import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='flex min-h-[100dvh] flex-col items-center justify-between p-6'>
      <body>{children}</body>
    </html>
  )
}
